version: "3.9"
services:
  postgres:
    container_name: generate-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yoyo
      POSTGRES_PASSWORD: yoyo5555
      POSTGRES_DB: generate-db

  redis:
    image: redis:latest
    container_name: generate-redis
    hostname: redis
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes", "--requirepass", "yoyo5555"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - "./pkg/redis/conf/generate.conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: yoyo5555

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generate-api
    volumes:
      - "./:./"
    working_dir: ./cmd
    ports:
      - 6476:6476
    depends_on:
      - postgres
      - redis

volumes:
  redis-data:
