// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "HEEPOKE Support",
            "url": "https://github.com/HEEPOKE",
            "email": "Damon1FX@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate/check-data": {
            "get": {
                "description": "Get Data From Key in Cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilities"
                ],
                "summary": "Get Data From Key in Cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/generate/get-details": {
            "get": {
                "description": "Get List All Generate Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate"
                ],
                "summary": "Get List All Generate Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/generate/mockup-data": {
            "post": {
                "description": "Get Auto Generate Mock up data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generate"
                ],
                "summary": "Get Auto Generate Mock up data",
                "parameters": [
                    {
                        "description": "GenerateRequestBody",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/examples.GenerateExample"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enums.Category": {
            "type": "string",
            "enum": [
                "name",
                "firstname",
                "lastname",
                "email",
                "tel",
                "password",
                "word",
                "sentence",
                "bool",
                "int",
                "int8",
                "int32",
                "int16",
                "int64",
                "uint",
                "uint8",
                "uint16",
                "uint32",
                "uint64",
                "float32",
                "float64",
                "byte",
                "rune"
            ],
            "x-enum-varnames": [
                "NAME",
                "FIRSTNAME",
                "LASTNAME",
                "EMAIL",
                "TEL",
                "PASSWORD",
                "WORD",
                "SENTENCE",
                "BOOL",
                "INT",
                "INT8",
                "INT32",
                "INT16",
                "INT64",
                "UINT",
                "UINT8",
                "UINT16",
                "UINT32",
                "UINT64",
                "FLOAT32",
                "FLOAT64",
                "BYTE",
                "RUNE"
            ]
        },
        "examples.GenerateExample": {
            "type": "object",
            "required": [
                "columns",
                "quantity",
                "table"
            ],
            "properties": {
                "columns": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/examples.GenerateOptions"
                    }
                },
                "key": {
                    "type": "string",
                    "example": ""
                },
                "quantity": {
                    "type": "integer",
                    "example": 1000
                },
                "table": {
                    "type": "string",
                    "example": "users"
                }
            }
        },
        "examples.GenerateOptions": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string",
                    "example": ""
                },
                "gen": {
                    "type": "boolean"
                },
                "length": {
                    "type": "integer"
                },
                "types": {
                    "$ref": "#/definitions/enums.Category"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6476",
	BasePath:         "/apis",
	Schemes:          []string{"http"},
	Title:            "Generate Mock-up API",
	Description:      "Auto Generate Mock-up Data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
