basePath: /apis
definitions:
  enums.Category:
    enum:
    - name
    - firstname
    - lastname
    - email
    - tel
    - password
    - word
    - sentence
    - bool
    - int
    - int8
    - int32
    - int16
    - int64
    - uint
    - uint8
    - uint16
    - uint32
    - uint64
    - float32
    - float64
    - byte
    - rune
    type: string
    x-enum-varnames:
    - NAME
    - FIRSTNAME
    - LASTNAME
    - EMAIL
    - TEL
    - PASSWORD
    - WORD
    - SENTENCE
    - BOOL
    - INT
    - INT8
    - INT32
    - INT16
    - INT64
    - UINT
    - UINT8
    - UINT16
    - UINT32
    - UINT64
    - FLOAT32
    - FLOAT64
    - BYTE
    - RUNE
  examples.FailedCommonResponse:
    properties:
      status:
        $ref: '#/definitions/examples.FailedStatusMessage'
    type: object
  examples.FailedStatusMessage:
    properties:
      code:
        example: "0001"
        type: string
      description:
        type: string
      message:
        example: Failed
        type: string
      service:
        type: string
    type: object
  examples.GenerateExample:
    properties:
      columns:
        additionalProperties:
          $ref: '#/definitions/examples.GenerateOptions'
        type: object
      key:
        example: ""
        type: string
      quantity:
        example: 1000
        type: integer
      table:
        example: users
        type: string
    required:
    - columns
    - quantity
    - table
    type: object
  examples.GenerateOptions:
    properties:
      default:
        example: ""
        type: string
      gen:
        type: boolean
      length:
        type: integer
      types:
        $ref: '#/definitions/enums.Category'
    type: object
  examples.GenerateResponseExample:
    properties:
      created_at:
        example: "2022-01-01 00:00:00"
        type: string
      deleted_at:
        example: "0001-01-01 00:00:00"
        type: string
      id:
        example: 1
        type: integer
      key:
        example: "123456"
        type: string
      quantity:
        example: 1000
        type: integer
      table:
        example: users
        type: string
      time_expired:
        example: "2022-01-01 00:00:00"
        type: string
      updated_at:
        example: "2022-01-01 00:00:00"
        type: string
    type: object
  examples.SuccessCheckDataFromKeyResponse:
    properties:
      payload:
        $ref: '#/definitions/models.JsonStructure'
      status:
        $ref: '#/definitions/examples.SuccessStatusMessage'
    type: object
  examples.SuccessGenerateGetAllResponse:
    properties:
      payload:
        $ref: '#/definitions/examples.GenerateResponseExample'
      status:
        $ref: '#/definitions/examples.SuccessStatusMessage'
    type: object
  examples.SuccessStatusMessage:
    properties:
      code:
        example: "0000"
        type: string
      description:
        type: string
      message:
        example: Success
        type: string
      service:
        type: string
    type: object
  models.JsonStructure:
    properties:
      datas:
        items:
          additionalProperties: true
          type: object
        type: array
      key:
        example: "123456"
        type: string
      quantity:
        example: 1000
        type: integer
      table:
        example: users
        type: string
    type: object
host: localhost:6476
info:
  contact:
    email: Damon1FX@gmail.com
    name: HEEPOKE Support
    url: https://github.com/HEEPOKE
  description: Auto Generate Mock-up Data
  title: Generate Mock-up API
  version: "1.0"
paths:
  /generate/get-details:
    get:
      consumes:
      - application/json
      description: Get List All Generate Data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/examples.SuccessGenerateGetAllResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/examples.FailedCommonResponse'
      summary: Get List All Generate Data
      tags:
      - Generate
  /generate/mockup-data:
    post:
      consumes:
      - application/json
      description: Get Auto Generate Mock up data
      parameters:
      - description: GenerateRequestBody
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/examples.GenerateExample'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/examples.SuccessCheckDataFromKeyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/examples.FailedCommonResponse'
      summary: Get Auto Generate Mock up data
      tags:
      - Generate
  /utilities/check-data:
    get:
      consumes:
      - application/json
      description: Get Data From Key in Cache
      parameters:
      - description: key
        example: "123456"
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/examples.SuccessCheckDataFromKeyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/examples.FailedCommonResponse'
      summary: Get Data From Key in Cache
      tags:
      - Utilities
schemes:
- http
swagger: "2.0"
