basePath: /apis
definitions:
  enums.Category:
    enum:
    - name
    - firstname
    - lastname
    - email
    - tel
    - password
    - word
    - sentence
    - bool
    - int
    - int8
    - int32
    - int16
    - int64
    - uint
    - uint8
    - uint16
    - uint32
    - uint64
    - float32
    - float64
    - byte
    - rune
    type: string
    x-enum-varnames:
    - NAME
    - FIRSTNAME
    - LASTNAME
    - EMAIL
    - TEL
    - PASSWORD
    - WORD
    - SENTENCE
    - BOOL
    - INT
    - INT8
    - INT32
    - INT16
    - INT64
    - UINT
    - UINT8
    - UINT16
    - UINT32
    - UINT64
    - FLOAT32
    - FLOAT64
    - BYTE
    - RUNE
  examples.GenerateExample:
    properties:
      columns:
        additionalProperties:
          $ref: '#/definitions/examples.GenerateOptions'
        type: object
      key:
        example: ""
        type: string
      quantity:
        example: 1000
        type: integer
      table:
        example: users
        type: string
    required:
    - columns
    - quantity
    - table
    type: object
  examples.GenerateOptions:
    properties:
      default:
        example: ""
        type: string
      gen:
        type: boolean
      length:
        type: integer
      types:
        $ref: '#/definitions/enums.Category'
    type: object
host: localhost:6476
info:
  contact:
    email: Damon1FX@gmail.com
    name: HEEPOKE Support
    url: https://github.com/HEEPOKE
  description: Auto Generate Mock-up Data
  title: Generate Mock-up API
  version: "1.0"
paths:
  /generate/check-data:
    get:
      consumes:
      - application/json
      description: Get Data From Key in Cache
      parameters:
      - description: key
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Data From Key in Cache
      tags:
      - Utilities
  /generate/get-details:
    get:
      consumes:
      - application/json
      description: Get List All Generate Data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get List All Generate Data
      tags:
      - Generate
  /generate/mockup-data:
    post:
      consumes:
      - application/json
      description: Get Auto Generate Mock up data
      parameters:
      - description: GenerateRequestBody
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/examples.GenerateExample'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      summary: Get Auto Generate Mock up data
      tags:
      - Generate
schemes:
- http
swagger: "2.0"
